spring.application.name=demo
spring.data.mongodb.uri=mongodb://aibelkacemi:Nac456123@localhost:27017/admin
server.port=8080
app.public-port=8082
app.initial-data.enabled=true
app.upload-dir=uploads
app.resource-photo-dir=resource-photos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
security.jwt.secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
